### ISSUE TITLE
Move JSON data tests into the "app" module

### ISSUE THREAD

**Issue by jaredsburrows** [NonameDev/MathApp#10]
**1. Move all JSON data test into app module**

**2. Add this to force all configurations to remove json, then we will add a different version:**

```
configurations {
     all*.exclude module: 'json'
}
```

**3. Add the JSON library to MathApp "app" module:**

```
dependencies {
   compile "org.json:json:20141113"
}
```

**Comment by acompagno** [comment]
This solution doesn't fully fix the problem. It gets rid of the error message, but the unit tests are still run using Android's Json lib. Closing until a new solution is found.

**Comment by jaredsburrows** [comment]
@acompagno  How do you know if it uses Android's JSON lib?

To be clear,  I should have said:

    configurations {
        all*.exclude module: 'org.json' // our module is called "json", so it conflicted
    }

Here is a test and it passes:

    @Test
    public void jsonTest() throws Exception {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("test", true);

        assertThat(jsonObject, not(nullValue()));
        assertThat((Boolean) jsonObject.get("test"), is(true));
    }

**Comment by jaredsburrows** [comment]
@acompagno  How do you know if it uses Android's JSON lib?

To be clear,  I should have said:

```
configurations {
    all*.exclude module: 'org.json' // our module is called "json", so it conflicted
}
```

### With `Robolectric`:

Here is a test and it passes:

```
@Test
public void jsonTest() throws Exception {
    JSONObject jsonObject = new JSONObject();
    jsonObject.put("test", true);

    assertThat(jsonObject, not(nullValue()));
    assertThat((Boolean) jsonObject.get("test"), is(true));
}
```

However, running `gradle :app:testDebug --tests="*ResourcesTest*"` with and without: 

```
configurations {
    all*.exclude module: 'org.json' // our module is called "json", so it conflicted
}
```

seems to work just fine.

### Without `Robolectric`:

It fails.

## Currently there is no support for `Robolectric` + `PowerMock`.

**Comment by jaredsburrows** [comment]
I think we are leaving this a separate module.

**Comment by acompagno** [comment]
I can move it in the future. Right now it isn't blocking anything. I'll reopen when i start working on it.
