### ISSUE TITLE
Implement Navigation Drawer

### ISSUE THREAD

**Issue by jaredsburrows** [NonameDev/MathApp#8]
I have not decided what would be best(http://www.google.com/design/spec/patterns/navigation-drawer.html#), here is a list of the most popular options without having to create one from scatch:
- Most Popular:
  - https://github.com/neokree/MaterialNavigationDrawer (10+ API and android support v7)
- Use a "template" instead of importing an Android Library:
  - https://github.com/kanytu/android-material-drawer-template (11+ API but very basic)
  - https://github.com/kanytu/Android-studio-material-template
- Not Sure:
  - https://github.com/balysv/material-menu (not sure)

**Comment by jaredsburrows** [comment]
@acompagno Which one do you like best?

**Comment by acompagno** [comment]
IDK. Might as well go with the most popular one

**Comment by jaredsburrows** [comment]
I am moving forward with: https://github.com/neokree/MaterialNavigationDrawer.

**Comment by jaredsburrows** [comment]
I just found this one: https://github.com/mikepenz/MaterialDrawer.

**Comment by jaredsburrows** [comment]
I am going to use the Material Drawer from Google: http://developer.android.com/tools/support-library/features.html#design.

Im consolidating this into https://github.com/NonameDev/MathApp/issues/20.
